# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_Courses.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/06_Courses.ipynb 2
from .table import Table, sh
from .sheet import Sheet
from nbdev import show_doc
import pandas as pd
import copy

# %% ../nbs/06_Courses.ipynb 9
@patch
def clean_df(self:Courses,
             sort_by:list=['Year', 'Q', 'Course'], # variable to sort by
             ascending:list=[True, True, True], # ascending?
            )->pd.DataFrame:  # cleaned dataframe
    """
    Clean the Service table.
    
    """
    df = copy.deepcopy(self.df)
    if not self.cumulative:
        df = self.clean_cumulative(df)
    df = Table.table_clean_df(self)
    df = df.sort_values(by=sort_by, ascending=ascending)
    return df
