# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_Lectures.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/07_Lectures.ipynb 2
from .table import Table, sh
from .sheet import Sheet
from nbdev import show_doc
import pandas as pd

# %% ../nbs/07_Lectures.ipynb 8
@patch
def clean_df(self:Lectures,
             sort_by:list=['Year', 'Month'], # variable to sort by
             ascending:bool=[True, True] # ascending?
            )->pd.DataFrame:  # cleaned dataframe
    """
    Clean the Lectures table.
    
    """
    df = Table.table_clean_df(self)
    df = df.sort_values(by=sort_by, ascending=ascending)
    return df
