# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_Service.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/03_Service.ipynb 2
from .table import Table, sh
from .sheet import Sheet
from nbdev import show_doc
import pandas as pd

# %% ../nbs/03_Service.ipynb 9
@patch
def clean_df(self:Service,
             sort_by:str='Year', # variable to sort by
             ascending:bool=True # ascending?
            )->pd.DataFrame:  # cleaned dataframe
    """
    Clean the Service table.
    
    """
    df = Table.table_clean_df(self)
    df = df.sort_values(by=[sort_by], ascending=[ascending])
    return df
