# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_sheet.ipynb.

# %% auto 0
__all__ = ['Sheet']

# %% ../nbs/01_sheet.ipynb 3
from gspread import oauth
import pandas as pd
from nbdev import show_doc
from fastcore.test import *
from fastcore.basics import *
from fastcore.foundation import *

# %% ../nbs/01_sheet.ipynb 4
class Sheet:
    def __init__(
            self,
            sheet_name:str, # name of the google sheet to access
            creds:str='credentials.json' # filename containing google auth credentials
        ):
        self.gc = oauth(credentials_filename=creds)
        self.sheet = self.gc.open(sheet_name)

# %% ../nbs/01_sheet.ipynb 6
@patch
def get_dataframe(
        self:Sheet, 
        worksheet:str,     # name of the worksheet to return
        headers:bool=True  # return headers?
    )->pd.DataFrame:       # dataframe containing worksheet data 
    """ returns a dataframe from a worksheet """
    wks = self.sheet.worksheet(worksheet)
    data = wks.get_all_values()
    if headers:
        headers = data.pop(0)
    else:
        headers = []
    df = pd.DataFrame(data, columns=headers)
    return df
